version: '3.9'

services:

  api:
    build: .
    container_name: purplle-api

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data

    restart: always

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000